--Стандартные параметры начисления кэшбэка
--CB_PERC   MIN_CB_AMOUNT   MAX_CB_AMOUNT   MIN_OPER_COL
INSERT INTO std_amount VALUES (1, 100, 3000, 10);
COMMIT;
/
--Заполение таблицы ошибок файлов
INSERT ALL
INTO FILE_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (20, 'FE000', 'CORRECT FILE')
INTO FILE_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (21, 'FE001', 'INCORRECT HEADER')
INTO FILE_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (22, 'FE002', 'INCORRECT TRAILER')
INTO FILE_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (23, 'FE003', 'INCORRECT FILE_DATE')
INTO FILE_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (24, 'FE004', 'FILE ALREADY PROCESSED')
INTO FILE_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (25, 'FE005', 'INCORRECT FIELD TYPE')
SELECT * FROM dual;
COMMIT;

--Заполнение таблицы ошибок строк
INSERT ALL
INTO STR_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (10, 'SE000', 'CORRECT STRING')
INTO STR_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (11, 'SE001', 'INCORRECT DATE')
INTO STR_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (12, 'SE002', 'INCORRECT CARD HASH')
INTO STR_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (13, 'SE003', 'UNKNOWN HEADER NUMBER')
INTO STR_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (14, 'SE004', 'UNKNOWN OR INCORRECT MCC')
INTO STR_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (15, 'SE005', 'UNKNOWN OR INCORRECT MERCHANT')
INTO STR_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (16, 'SE006', 'INCORRECT STRING TYPE')
INTO STR_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (17, 'SE007', 'INCORRECT FILE')
INTO STR_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (18, 'SE008', 'PURCHASE ALREADY PROCESSED')
INTO STR_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (19, 'SE009', 'REFUSE ALREADY PROCESSED')
INTO STR_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (110, 'SE010', 'OLD TRANSACTION')
INTO STR_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (111, 'SE011', 'TRANSACTION FROM THE FUTURE')
INTO STR_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (112, 'SE012', 'SUM OF RETURN GREATER THAN SUM OF PURCHASE')
INTO STR_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (113, 'SE013', 'CARD IS NOT FOUND')
INTO STR_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (114, 'SE014', 'MORE THAN ONE CARD FOUND')
INTO STR_ERROR_CODES ("ID", "E_CODE", "TEXT") VALUES (115, 'SE015', 'PURCHASE FOR REFUSE NOT FOUND')
SELECT * FROM dual;
COMMIT;
/
--Заполнение таблицы статусов файлов
INSERT ALL
INTO file_state VALUES (30, 'NEW')
INTO file_state VALUES (31, 'IN PROGRESS')
INTO file_state VALUES (32, 'PROCESSED')
INTO file_state VALUES (33, 'REFUSED')
SELECT * FROM dual;
COMMIT;
