
--Заполение таблицы мерчантов
SELECT * FROM MERCHANTS;
INSERT INTO MERCHANTS ("ID", "MERCHANT_NAME", "AMOUNT_PERCENT", "START_DATE", "END_DATE", "MERCHANT_CATEGORY_ID", "TRANS_PREFIX") VALUES 
       (SEQ_MCC_MERCH_ID.nextval, 'AEROFLOT', 2, trunc (SYSDATE, 'MM'),trunc (last_day(sysdate)),
       (SELECT ID FROM MCC_CODES M WHERE MCC = 3011), 'AFT');
INSERT INTO MERCHANTS ("ID", "MERCHANT_NAME", "AMOUNT_PERCENT", "START_DATE", "END_DATE", "MERCHANT_CATEGORY_ID", "TRANS_PREFIX") VALUES 
       (SEQ_MCC_MERCH_ID.nextval, 'TRANSAERO', NULL, trunc (SYSDATE, 'MM'),trunc (last_day(sysdate)),
       (SELECT ID FROM MCC_CODES M WHERE MCC = 3089), 'TSA');       
INSERT INTO MERCHANTS ("ID", "MERCHANT_NAME", "AMOUNT_PERCENT", "START_DATE", "END_DATE", "MERCHANT_CATEGORY_ID", "TRANS_PREFIX") VALUES 
       (SEQ_MCC_MERCH_ID.nextval, 'S7 Airlines', 1.5, trunc (SYSDATE, 'MM'),trunc (last_day(sysdate)),
       (SELECT ID FROM MCC_CODES M WHERE MCC = 4112), 'S7A');  	   
INSERT INTO MERCHANTS ("ID", "MERCHANT_NAME", "AMOUNT_PERCENT", "START_DATE", "END_DATE", "MERCHANT_CATEGORY_ID", "TRANS_PREFIX") VALUES 
       (SEQ_MCC_MERCH_ID.nextval, 'MTS', 2, trunc (SYSDATE, 'MM'),trunc (last_day(sysdate)),
       (SELECT ID FROM MCC_CODES M WHERE MCC = 4812), 'MTS');  	   
INSERT INTO MERCHANTS ("ID", "MERCHANT_NAME", "AMOUNT_PERCENT", "START_DATE", "END_DATE", "MERCHANT_CATEGORY_ID", "TRANS_PREFIX") VALUES 
       (SEQ_MCC_MERCH_ID.nextval, 'MTS.RU', 2, trunc (SYSDATE, 'MM'),trunc (last_day(sysdate)),
       (SELECT ID FROM MCC_CODES M WHERE MCC = 4814), 'OMTS');  	
INSERT INTO MERCHANTS ("ID", "MERCHANT_NAME", "AMOUNT_PERCENT", "START_DATE", "END_DATE", "MERCHANT_CATEGORY_ID", "TRANS_PREFIX") VALUES 
       (SEQ_MCC_MERCH_ID.nextval, 'NOVOTELEKOM', 2, trunc (SYSDATE, 'MM'),trunc (last_day(sysdate)),
       (SELECT ID FROM MCC_CODES M WHERE MCC = 4814), 'NTK');  	
INSERT INTO MERCHANTS ("ID", "MERCHANT_NAME", "AMOUNT_PERCENT", "START_DATE", "END_DATE", "MERCHANT_CATEGORY_ID", "TRANS_PREFIX") VALUES 
       (SEQ_MCC_MERCH_ID.nextval, 'NOVOSIBIRSKENERGO', NULL, trunc (SYSDATE, 'MM'),trunc (last_day(sysdate)),
       (SELECT ID FROM MCC_CODES M WHERE MCC = 4900), 'NSKE'); 	 
INSERT INTO MERCHANTS ("ID", "MERCHANT_NAME", "AMOUNT_PERCENT", "START_DATE", "END_DATE", "MERCHANT_CATEGORY_ID", "TRANS_PREFIX") VALUES 
       (SEQ_MCC_MERCH_ID.nextval, 'LEROY MERLIN', NULL, trunc (SYSDATE, 'MM'),trunc (last_day(sysdate)),
       (SELECT ID FROM MCC_CODES M WHERE MCC = 5261), 'LMR'); 	
INSERT INTO MERCHANTS ("ID", "MERCHANT_NAME", "AMOUNT_PERCENT", "START_DATE", "END_DATE", "MERCHANT_CATEGORY_ID", "TRANS_PREFIX") VALUES 
       (SEQ_MCC_MERCH_ID.nextval, 'MONETKA', NULL, trunc (SYSDATE, 'MM'),trunc (last_day(sysdate)),
       (SELECT ID FROM MCC_CODES M WHERE MCC = 5411), 'MNK');
INSERT INTO MERCHANTS ("ID", "MERCHANT_NAME", "AMOUNT_PERCENT", "START_DATE", "END_DATE", "MERCHANT_CATEGORY_ID", "TRANS_PREFIX") VALUES 
       (SEQ_MCC_MERCH_ID.nextval, 'IKEA', NULL, trunc (SYSDATE, 'MM'),trunc (last_day(sysdate)),
       (SELECT ID FROM MCC_CODES M WHERE MCC = 5499), 'IKEA'); 	
INSERT INTO MERCHANTS ("ID", "MERCHANT_NAME", "AMOUNT_PERCENT", "START_DATE", "END_DATE", "MERCHANT_CATEGORY_ID", "TRANS_PREFIX") VALUES 
       (SEQ_MCC_MERCH_ID.nextval, 'M.VIDEO', NULL, trunc (SYSDATE, 'MM'),trunc (last_day(sysdate)),
       (SELECT ID FROM MCC_CODES M WHERE MCC = 5722), 'MV'); 	
INSERT INTO MERCHANTS ("ID", "MERCHANT_NAME", "AMOUNT_PERCENT", "START_DATE", "END_DATE", "MERCHANT_CATEGORY_ID", "TRANS_PREFIX") VALUES 
       (SEQ_MCC_MERCH_ID.nextval, 'CITILINK', NULL, trunc (SYSDATE, 'MM'),trunc (last_day(sysdate)),
       (SELECT ID FROM MCC_CODES M WHERE MCC = 5732), 'CTL'); 	
INSERT INTO MERCHANTS ("ID", "MERCHANT_NAME", "AMOUNT_PERCENT", "START_DATE", "END_DATE", "MERCHANT_CATEGORY_ID", "TRANS_PREFIX") VALUES 
       (SEQ_MCC_MERCH_ID.nextval, 'PAPA JOHNS', NULL, trunc (SYSDATE, 'MM'), trunc (last_day(sysdate)),
       (SELECT ID FROM MCC_CODES M WHERE MCC = 5812), 'PJ'); 	   
COMMIT;
/
select * from merchants;

